### ISSUE TITLE
I need some help.

### ISSUE THREAD

**Issue by mikhoul** [Tetr4/Radio#1]
I've installed Android Studio and I try to compile the project and I receive this error: 
Error:(7, 1) A problem occurred evaluating project ':app'.
> K:\AndroidProjects\Radio-master777\keystore.properties (file not found)

Do you have any hint where I can find this file since I'm new with Android Studio ?

Regards ! :octocat:

**Comment by mikhoul** [comment]
I answer to my own request so if somebody else have the same issue it will help: 

Ok the problem I had is that the project don't have included a KEY to sign the app.

So I generated a key  using this command: 

`K:\AndroidStudio\jre\bin>keytool -genkey -v -keystore release.keystore -alias MyOwnAliasHere -keyalg RSA -keysize 2048 -validity 10000`

So at the end it generated a file (the key) named "release.keystore". This file contained my "store password", "keypassword" and my "Alias". I've put this file in the root of the project .

After I created a text file named "keystore.properties" containing the path of the variable from the "build.gradle"

Here's the format for the file "keystore.properties" that should be put also in the root of the project.

```
storePassword=myPassword
keyPassword=myPassword
keyAlias=MyAlias
storeFile=../release.keystore
```

I have also added a line to the file "local.properties" , Here's the line:
 `keystore.props.file=../keystore.properties`

Also don't forget to install the same SDK version as stated in the build.graddle (25.0.2 as of today).
To instal it use the SDK manager from the Android Studio and don't forget to enable the "Show package Details" to be able to select a version in the "SDK tools" tab.

After that everything should compile fine and you should have a usable APK. 


I admit I don't understand all the process since it's only since 2-3 days ago I have installed Android Studio but being self taught with google I've been able to figure how to make it work  😺 .


Regards :octocat:

**Comment by Tetr4** [comment]
Hi mikhoul, thanks for your feedback!

I updated the build files (bf8791b1fa8a12206271a4566d3b1572f3030a16), made the keystore file optional and added an example `keystore.properties.sample` file (b9b8f22ac975fcb8a215b9eee743f56390d0c6cf), so the project can be build directly without a keystore.

Best regards :bowtie:

**Comment by mikhoul** [comment]
Thanks ! 

I learned a lot trying to compile this project about Android Studio...

Next I will have to learn how to use Gradle, I understand his purpose but I don't understand how to use it myself. 

Wishing you a great day :octocat:
